sonar.projectKey=leel-swivel_aws-serverless-ads-api
sonar.organization=leel-swivel

sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.test.ts

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8